version: "2"
version: '3'

services:
    app:
        build:
            context: .
        # restart: always
        volumes:
            - ./:/app
            - /staticfile:/staticfile
        ports:
            - "8800:8800"
        env_file:
            - .env
        links:
            - redis

    redis:
        image: redis:alpine
