# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OauthAccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=150, unique=True)),
                ('refresh_token', models.CharField(max_length=150, unique=True)),
                ('expired_at', models.DateTimeField(null=True)),
                ('is_refresh_token_used', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'oauth_access_token',
            },
        ),
        migrations.CreateModel(
            name='OauthClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_public_key', models.CharField(max_length=100, unique=True)),
                ('client_secret_key', models.CharField(max_length=100, unique=True)),
                ('callback_url', models.CharField(max_length=255, unique=True)),
                ('is_enabled', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], max_length=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'oauth_clients',
            },
        ),
        migrations.CreateModel(
            name='OauthGrant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_code', models.CharField(max_length=100, unique=True)),
                ('ip_address', models.CharField(max_length=50)),
                ('revoked', models.SmallIntegerField(db_column=b'revoked', default=False)),
                ('created_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(db_column=b'client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.OauthClient')),
            ],
            options={
                'db_table': 'oauth_grants',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=70, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30, null=True)),
                ('confirmation_code', models.CharField(max_length=150, null=True, unique=True)),
                ('confirmed_account', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=1)),
                ('is_admin', models.CharField(choices=[(b'Y', b'Yes'), (b'N', b'No')], default=b'N', max_length=1)),
                ('path', models.CharField(max_length=50, null=True)),
                ('profile_picture', models.CharField(max_length=100, null=True)),
                ('last_login', models.DateTimeField(null=True)),
                ('last_login_ip_address', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='oauthgrant',
            name='user',
            field=models.ForeignKey(db_column=b'user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='client',
            field=models.ForeignKey(db_column=b'client_id', on_delete=django.db.models.deletion.CASCADE, to='login.OauthClient'),
        ),
        migrations.AddField(
            model_name='oauthaccesstoken',
            name='user',
            field=models.ForeignKey(db_column=b'user_id', on_delete=django.db.models.deletion.CASCADE, to='login.User'),
        ),
    ]
