# Generated by Django 2.2.12 on 2020-05-15 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Client'),
        ),
        migrations.AddField(
            model_name='grant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Client'),
        ),
        migrations.AddField(
            model_name='grant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_key', 'revoked'], name='oauth_clien_client__8ac8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['secret_key', 'revoked'], name='oauth_clien_secret__bac795_idx'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Client'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['reference_number', 'otp', 'revoked', 'expired_at'], name='oauth_verif_referen_b111dd_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address', 'revoked'], name='oauth_ipadd_ip_addr_5f311e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ipaddress',
            unique_together={('ip_address', 'client')},
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['code', 'client', 'revoked', 'expired_at'], name='oauth_grant_code_491c85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grant',
            unique_together={('code', 'client')},
        ),
        migrations.AddIndex(
            model_name='accesstoken',
            index=models.Index(fields=['access_token', 'revoked_access_token', 'access_token_expired_at'], name='oauth_acces_access__d59027_idx'),
        ),
    ]
