# Generated by Django 2.2.12 on 2020-05-10 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddField(
            model_name='ipaddress',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Client'),
        ),
        migrations.AddField(
            model_name='grant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Client'),
        ),
        migrations.AddField(
            model_name='grant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_key', 'active'], name='oauth_clien_client__8d1451_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['secret_key', 'active'], name='oauth_clien_secret__9c7f40_idx'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='oauth.Client'),
        ),
        migrations.AddField(
            model_name='accesstoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.User'),
        ),
        migrations.AddIndex(
            model_name='verification',
            index=models.Index(fields=['reference_number', 'otp', 'client', 'is_used', 'expired_at'], name='oauth_verif_referen_807a8a_idx'),
        ),
        migrations.AddIndex(
            model_name='ipaddress',
            index=models.Index(fields=['ip_address', 'revoked'], name='oauth_ipadd_ip_addr_5f311e_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['code', 'client', 'revoked', 'expired_at'], name='oauth_grant_code_491c85_idx'),
        ),
    ]
